import { ICategoriesItem } from "./SharedCategories.type";

export const categoriesList: ICategoriesItem[]= [
  {text: 'Блоги', number: '12.4k'},
  {text: 'Новости', number:'23.7k'},
  {text: 'Юмор и развлечение', number:'184.4k'},
  {text: 'Технологии', number:'31.5k'},
  {text: 'Экономика', number:'69.6k'},
  {text: 'Бизнес и стартапы', number:'90.2k'},
  {text: 'Криптовалюты', number:'100.4k'},
  {text: 'Путешествия', number:'400.0k'},
  {text: 'Маркетинг, PR, реклама', number:'76.5k'},
  {text: 'Психология', number:'1.2k'},
  {text: 'Дизайн', number:'59.3k'},
  {text: 'Политика', number:'120.0k'},
  {text: 'Исскуство', number:'58.8k'},
  {text: 'Право', number:'15.1k'},
  {text: 'Образование', number:'80.8k'},
  {text: 'Книги', number:'71.1k'},
  {text: 'Лингвистика', number:'20.2k'},
  {text: 'Карьера', number:'45.7k'},
  {text: 'Познавательное', number:'200.7k'},
  {text: 'Курсы и гайды', number:'166.6k'},
  {text: 'Спорт', number:'11.1k'},
  {text: 'Мода и красота', number:'45.5k'},
  {text: 'Медицина', number:'78.8k'},
  {text: 'Здоровье и Фитнес', number:'59.5k'},
  {text: 'Картинки и фото', number:'161.4k'},
  {text: 'Софт и приложение', number:'41.1k'},
  {text: 'Видео и фильмы', number:'11.9k'},
  {text: 'Музыка', number:'56.6k'},
  {text: 'Игры', number:'90.4k'},
  {text: 'Еда и кулинария', number:'89.0k'},
  {text: 'Цитаты', number:'44.4k'},
  {text: 'Рукоделие', number:'27.7k'},
]