export const PERMISSIONS_SCOPES  = {
  CAN_CHECK_CHANNEL: 'CAN_CHECK_CHANNEL',
  CAN_PUBLIC_CHANNEL: 'CAN_PUBLIC_CHANNEL',
  CAN_SEND_VALID_MESSAGE: 'CAN_SEND_VALID_MESSAGE',
  CAN_BUY: 'CAN_BUY',
  CAN_BAN: 'CAN_BAN',
  CAN_PARDON: 'CAN_PARDON',
  CAN_USER_UPDATE: 'CAN_USER_UPDATE',
  CAN_VALIDATE: 'CAN_VALIDATE'
} as const;
